### ISSUE TITLE
Plain API-key over http

### ISSUE THREAD

**Issue by abij** [ShellRechargeSolutionsEU/oplaadpalen-client#1]
The client connects over the http-link. The devKey is part of the url and easy to 'sniff'.
This should communicate over https, using TLS-encryption for the key.

https://github.com/NewMotion/oplaadpalen-client/blob/8bdd30df74fa7b6bba54b1b97fa4cfe531b6717a/src/main/scala/com/thenewmotion/oplaadpalen/Client.scala#L30

**Comment by poohsen** [comment]
thanks @abij . This repo is deprecated (to put it mildly). If you want to connect to oplaadpalen these days you should use the OCPI protocol.
